language: node_js
node_js:
  - 6
  - 4
  - 0.12
  - 0.10
  - 0.8
  - 0.6
sudo: false
env:
  - CXX=g++-4.8
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
  - codeclimate-test-reporter < reports/coverage/lcov.info