language: node_js
node_js:
  - "node"
  - "6"
  - "4"
sudo: false
env:
  - CXX=g++-4.8
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
  - codeclimate-test-reporter < reports/coverage/lcov.info